ExoticSpecies/Models/Homeland.cs
/*
    Author: Alex Yoo
    Content: Original homelands of exotic species.
    Usage: constructor
*/
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExoticSpeciesOfTheNorth.Models
{
    public class Homeland
    {
        public int HomelandId { get; set; }

        [Display(Name = "Homeland Name")]
        public string HomelandName { get; set; }

        public virtual List<Species> HomelandSpecies { get; set; }
    }
}

ExoticSpecies/Controllers/HomelandsController.cs
/*
    Author: Alex Yoo
    Content: All possible homelands of species around the world. Scaffolded code unchanged.
    Usage: ~/Homelands
*/
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExoticSpeciesOfTheNorth.Models;

namespace ExoticSpeciesOfTheNorth.Controllers
{
    public class HomelandsController : Controller
    {
        private ExoticSpeciesDbContext db = new ExoticSpeciesDbContext();

        // GET: Homelands
        public ActionResult Index()
        {
            return View(db.MyHomelands.ToList());
        }

        // GET: Homelands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homeland homeland = db.MyHomelands.Find(id);
            if (homeland == null)
            {
                return HttpNotFound();
            }
            return View(homeland);
        }

        // GET: Homelands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Homelands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HomelandId,HomelandName")] Homeland homeland)
        {
            if (ModelState.IsValid)
            {
                db.MyHomelands.Add(homeland);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(homeland);
        }

        // GET: Homelands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homeland homeland = db.MyHomelands.Find(id);
            if (homeland == null)
            {
                return HttpNotFound();
            }
            return View(homeland);
        }

        // POST: Homelands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HomelandId,HomelandName")] Homeland homeland)
        {
            if (ModelState.IsValid)
            {
                db.Entry(homeland).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(homeland);
        }

        // GET: Homelands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homeland homeland = db.MyHomelands.Find(id);
            if (homeland == null)
            {
                return HttpNotFound();
            }
            return View(homeland);
        }

        // POST: Homelands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Homeland homeland = db.MyHomelands.Find(id);
            db.MyHomelands.Remove(homeland);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExoticSpecies/Controllers/SpeciesController.cs
/*
    Author: Alex Yoo
    Content: Species CRUD code. Custom partial view: _SpeciesForHomeland.
    Usage: ~/Species
*/
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExoticSpeciesOfTheNorth.Models;

namespace ExoticSpeciesOfTheNorth.Controllers
{
    public class SpeciesController : Controller
    {
        private ExoticSpeciesDbContext db = new ExoticSpeciesDbContext();

        public PartialViewResult _IndexImages()
        {
            return PartialView();
        }

        // Custom partial view. Returns
        public PartialViewResult _SpeciesForHomeland(int homelandId)
        {
            var mySpecies = db.MySpecies.Where(ms => ms.HomelandId == homelandId);

            return PartialView(mySpecies.ToList());
        }

        // GET: Species
        public async Task<ActionResult> Index()
        {
            var mySpecies = db.MySpecies.Include(s => s.SpeciesHomeland);
            return View(await mySpecies.ToListAsync());
        }

        // GET: Species/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Species species = await db.MySpecies.FindAsync(id);
            if (species == null)
            {
                return HttpNotFound();
            }
            return View(species);
        }

        // GET: Species/Create
        public ActionResult Create()
        {
            ViewBag.HomelandId = new SelectList(db.MyHomelands, "HomelandId", "HomelandName");
            return View();
        }

        // POST: Species/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "SpeciesId,SpeciesName,HomelandId")] Species species)
        {
            if (ModelState.IsValid)
            {
                db.MySpecies.Add(species);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.HomelandId = new SelectList(db.MyHomelands, "HomelandId", "HomelandName", species.HomelandId);
            return View(species);
        }

        // GET: Species/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Species species = await db.MySpecies.FindAsync(id);
            if (species == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomelandId = new SelectList(db.MyHomelands, "HomelandId", "HomelandName", species.HomelandId);
            return View(species);
        }

        // POST: Species/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "SpeciesId,SpeciesName,HomelandId")] Species species)
        {
            if (ModelState.IsValid)
            {
                db.Entry(species).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.HomelandId = new SelectList(db.MyHomelands, "HomelandId", "HomelandName", species.HomelandId);
            return View(species);
        }

        // GET: Species/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Species species = await db.MySpecies.FindAsync(id);
            if (species == null)
            {
                return HttpNotFound();
            }
            return View(species);
        }

        // POST: Species/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Species species = await db.MySpecies.FindAsync(id);
            db.MySpecies.Remove(species);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExoticSpecies/Views/Homelands/Create.cshtml
@model ExoticSpeciesOfTheNorth.Models.Homeland

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Homeland</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HomelandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomelandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomelandName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExoticSpecies/Views/Homelands/Delete.cshtml
@model ExoticSpeciesOfTheNorth.Models.Homeland

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Homeland</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HomelandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomelandName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ExoticSpecies/Views/Homelands/Details.cshtml
@model ExoticSpeciesOfTheNorth.Models.Homeland

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Homeland</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HomelandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomelandName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HomelandId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ExoticSpecies/Views/Homelands/Edit.cshtml
@model ExoticSpeciesOfTheNorth.Models.Homeland

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Homeland</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HomelandId)

        <div class="form-group">
            @Html.LabelFor(model => model.HomelandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomelandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomelandName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExoticSpecies/Views/Homelands/Index.cshtml
@* 
    Author: Alex Yoo
    Content: Search all homelands and species for text. Accordion affect on homeland heading, hiding species.
    Usage: return View()
*@

@model IEnumerable<ExoticSpeciesOfTheNorth.Models.Homeland>

@{
    ViewBag.Title = "Homelands";
}

@section styles {
    @Styles.Render("~/Content/css/Homelands")
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div>
    <input type="text" id="input-search" value="Search" />
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HomelandName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="tr-search">
            <td>
                <h3 class="h3-accordion">@Html.DisplayFor(modelItem => item.HomelandName)</h3>
                @{ Html.RenderAction("_SpeciesForHomeland", "Species", new { homelandId = item.HomelandId }); }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.HomelandId }) |
                @Html.ActionLink("Details", "Details", new { id = item.HomelandId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.HomelandId })
            </td>
        </tr>
    }

</table>

@section scripts {
    <script>
        //Search homelands and species
        var listItems = $(".tr-search");
        var inputSearch = $("#input-search");

        function searchTerms() {
            var inputSearchTerms = $("#input-search").val().toLowerCase();

            for (i = 0; i < listItems.length; i++) {
                var listItemValue = listItems[i].innerHTML.toLowerCase();

                if (listItemValue.indexOf(inputSearchTerms) > -1) {
                    listItems[i].style.display = "";
                }
                else {
                    listItems[i].style.display = "none";
                }
            }
        }
        inputSearch.select();
        inputSearch.on("focus", function () {
            $(this).select();
        });
        inputSearch.on("keyup", searchTerms);

        //Accordion homeland for species
        $(".h3-accordion").on("click", function () {
            var myContent = $(this).next();
            
            if (myContent.css("display") === "none")
            {
                myContent.show();
                $(".arrow").remove();
            }
            else
            {
                myContent.hide();
                $(this).append("<span class='arrow'>&raquo;</span>");
            }
        });
    </script>
}